lexicon: 1
id: io.github.atweb.site
defs:
  main:
    type: record
    key: literal:self
    description: >-
      An atweb website's metadata.
    record:
      type: object
      required:
        - createdAt
      properties:
        title:
          type: string
          description: A descriptive title for the website, if any.
        icon:
          type: string
          description: Link to a remote icon image for the website, if any.
        description:
          type: string
          description: Website description, if any.
        index:
          type: string
          format: at-uri
          default: 'index.mdx'
          description: >-
            Link to the entry point (index page) for this website.
            Defaults to index.mdx.
        createdAt:
          type: string
          format: datetime
          description: This record's creation date.
